apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service-deployment
  labels:
    app: chat-service-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-service-pod
  template:
    metadata:
      labels:
        app: chat-service-pod
    spec:
      containers:
        - name: chat-service-pod
          image: mingle-chat-service
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: chat-service-external
spec:
  selector:
    app: chat-service-pod
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 30000

